### ISSUE TITLE
Failing to match OTU IDs 

### ISSUE THREAD

**Issue by nejcstopno** [DaliangNing/iCAMP1#1]
Hi Daliang,
While running iCAMP pipeline (icamp.test.r) on my own dataset it is failing to match OTU IDs (Step #5). However, I am not sure why this issue comes up since all tree tip labels match the OTU names in the count and taxonomy tables.

```
> summary(tree$tip.label %in% colnames(comm))
  Mode    TRUE 
logical   22003

> summary(tree$tip.label %in% (clas$SpeciesID))
   Mode    TRUE 
logical   22003 
```

Any suggestions on what to change? 

I generated the nwk tree in QIIME2, imported it into R and done some filtering using phyloseq. I exported the final tree using the phy_tree() function from the phyloseq package and saved it as .nwk with write.tree() function from the ape package.

**Comment by DaliangNing** [comment]
You may send me (ningdaliang@ou.edu) the files and your code for a test : )
