### ISSUE TITLE
abundance weighted bMNTD & bNTI

### ISSUE THREAD

**Issue by adityabandla** [DaliangNing/iCAMP1#15]
Hi Ning,

When comm is the raw counts matrix (i.e. no rarefaction or total sum scaling), how is abundance weighting done when bMNTD & bNTI are calculated? From the bMNTD function, I see that when abundance.weighted = TRUE, the counts are transformed into relative proportions before being multiplied with MNTD. Is my reading of how the function works correct?

Regards, Adi

**Comment by DaliangNing** [comment]
Yes, the counts will be transformed to relative proportions (relative abundances) before calculating MNTD or betaMNTD. You may find the code 'comm.p = comm/rowSums(comm)' in the functions mntdn, bmntd, and bmntd.big.

I follow the equations in Dr. Stegen's paper (Stegen et al 2012 ISME J; [https://doi.org/10.1038/ismej.2012.22](https://doi.org/10.1038/ismej.2012.22)).

**Comment by adityabandla** [comment]
Thanks, Ning!
