### ISSUE TITLE
OpenBLAS blas_thread_init: pthread_create failed for thread in betaMPD calculation

### ISSUE THREAD

**Issue by heavennew** [DaliangNing/iCAMP1#16]
Hi Daliang, 
     When I used the iCAMP package to calculate betaMPD, some problems happened. I have set the thread numbers before I used the R code. Typed the code like this: export OPENBLAS_NUM_THREADS=10
However, the problems are still here. I have no idea how to deal with these problems.  

the error information is following:
----bMPD bin i=14 in 200 ---- Sun Sep 26 01:49:55 2021
Now calculating observed betaMPD. Begin at Sun Sep 26 01:49:55 2021. Please wait...
Now randomizing by parallel computing. Begin at Sun Sep 26 01:49:58 2021. Please wait...
Now fixing special cases. Begin at Sun Sep 26 01:52:01 2021. Please wait...
All match very well.
Now calculating observed MPD. Begin at Sun Sep 26 01:52:01 2021. Please wait...
Now randomizing by parallel computing. Begin at Sun Sep 26 01:52:04 2021. Please wait...
OpenBLAS blas_thread_init: pthread_create failed for thread 76 of 80: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 6191435 max
OpenBLAS blas_thread_init: pthread_create failed for thread 77 of 80: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 6191435 max
OpenBLAS blas_thread_init: pthread_create failed for thread 78 of 80: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 6191435 max
OpenBLAS blas_thread_init: pthread_create failed for thread 79 of 80: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 6191435 max
(END)

**Comment by DaliangNing** [comment]
I have no idea. It looks like the server has some limitations on the number of threads or processes. iCAMP functions usually have an option 'nworker' to set parallel threads; you may change the setting. Probably, you need to contact the server administrator or search online for a possible solution.

**Comment by DaliangNing** [comment]
If no more questions, I will close this issue soon.

**Comment by heavennew** [comment]
Hi Daliang, 
I am so sorry for not replying in time. I've solved this issue and it's no longer a problem. 
Thank you very much!
