### ISSUE TITLE
Error occured while runwhile bNRI.bin.big

### ISSUE THREAD

**Issue by PicaPicaLX** [DaliangNing/iCAMP1#18]

**Comment by PicaPicaLX** [comment]
Dear Ning,

I encountered some errors when running the `bNRI.bin.big()` function on my data. This is the output message:

> The names are re-ranked.
> Now calculating observed betaMPD. Begin at Thu Nov 25 10:16:50 2021. Please wait...
> Now randomizing by parallel computing. Begin at Thu Nov 25 10:16:57 2021. Please wait...
> Error in checkForRemoteErrors(val) : 
>  6 nodes produced errors; first error: error in evaluating the argument 'obj' in selecting a method for function 'attach.resource': cannot open the connection
> In addition: Warning messages:
> 1: In .Internal(gc(verbose, reset, full)) :
>   closing unused connection 4 (<-DESKTOP-8EQI7AV:11225)
> 2: In .Internal(gc(verbose, reset, full)) :
>   closing unused connection 3 (<-DESKTOP-8EQI7AV:11225)

I don't think there is something wrong with my data, because the same data can work normally on the `bNTI.bin.big()` function

I rerun `bNRI.bin.big()` with the `example.data` according to the help document and still prompt the same error.

I don't think I can solve this problem, so I'm here to ask for your help. 

It would be great if you could tell me what happened :)

**Comment by PicaPicaLX** [comment]
Here is my laptop's info:

OS: Windows 10 Pro 21H2, build 19044.1387
Processor: Intel Core i7-7700HQ
RAM: 2x8GB
R-4.1.0 x64
RStudio-2021.09.0 build 351
iCAMP v1.3.4 (Install directly using `install.packages()` from CRAN)

I hope this information is useful.

**Comment by DaliangNing** [comment]
You may try the latest version (1.5.3)
[https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions)

If not work either, please send me (ningdaliang@ou.edu) your file and R code for a test.

**Comment by DaliangNing** [comment]
Has your problem been solved with the latest version of iCAMP?

If no more questions, I will close the issue soon.

**Comment by PicaPicaLX** [comment]
Thank you very much for your reply. I have solved this problem after using the latest version.
