### ISSUE TITLE
Mismatch in values between vegdist Bray distances and RC.pc CB.obs

### ISSUE THREAD

**Issue by MagdaGarbowski** [DaliangNing/iCAMP1#19]
Dear Dr. Ning, 

I am curious as to why I am getting different observed Bray-Curtis dissimilarity values when using vegdist (method = "bray) and RC.pc(taxo.metric = "bray"). 

If you know what might be going on, I would appreciate hearing your thoughts. 

Thank you, 
Magda 

Code using the example data from the iCAMP package: 

data("example.data")
comm=example.data$comm
rand.time=20 
nworker=2 

RC=RC.pc(comm=comm, rand = rand.time,
         nworker = nworker, weighted = TRUE,
         output.bray = TRUE,
         taxo.metric = "bray",
         sig.index="RC")

RC$BC.obs

vegdist(comm, method = "bray")

**Comment by DaliangNing** [comment]
RC.pc standardized the counts to relative abundances before calculating Bray-Curtis index.
You may check
vegan::vegdist(comm/rowSums(comm), method = "bray")

**Comment by MagdaGarbowski** [comment]
Thank you Dr. Ning for your quick response! 

Best wishes, 
Magda
