### ISSUE TITLE
"Invalide 'size' argument" using the RC.pc function

### ISSUE THREAD

**Issue by Benjamingroult** [DaliangNing/iCAMP1#2]
Hi  @DaliangNing ,

I'm using the `RC.pc` function witch works well on my raw data. But when i rarefy and normalized my data with log and hellinger, I have the error: 

> Error in checkForRemoteErrors(val) : 
>   4 nodes produced errors; first error: invalid 'size' argument

I've tried with the `phyloseq` data set `Globalpatterns`and i'm facing the same issue.
Do you know how to solve this problem?

```
library(vegan)
library(phyloseq)
library(iCAMP)
data(GlobalPatterns)
sort(sample_sums(GlobalPatterns))
GlobalPatterns <- rarefy_even_depth(GlobalPatterns,sample.size = 50000)
count <- t(as(otu_table(GlobalPatterns), "matrix"))
count <- log1p(count)
count <- as.data.frame(decostand (count, 'hellinger'))
RCbray <- RC.pc(count, rand = 1000, weighted = TRUE)
```

**Comment by DaliangNing** [comment]
The null model requires integers in the OTU (or ASV) table. You may use the rarefied table. Let me know if it is very important for your study to use log+hellenger transformation before calculating beta diversity index. I can update the code within this or next week.

**Comment by Benjamingroult** [comment]
Yes it works with the rarefied table, but it would be very useful if you can adapt the code for non integers values. Thank you for your time, it would be very appreciated.

**Comment by adityabandla** [comment]
@DaliangNing I have a use case where I am trying to take the average of several samples taken from a single plot, would be great if I can make use of the normalised otu counts (relative abundance)

**Comment by DaliangNing** [comment]
Sorry for my late responses (a busy 'proposal season'). I got some ideas to make the null model work for propositional data, have an option to add some popular transformation (e.g. log+hellenger), or even customed beta-diversity function. I will try to do this in the next two to three weeks.

**Comment by DaliangNing** [comment]
The newest version of iCAMP (version >= 1.4.3, can be found [/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions)) has allowed to use relative abundance (values < 1) as input community matrix.

**Comment by DaliangNing** [comment]
@Benjamingroult please let me know if the new version (1.4.3) can address your concern. I will close this issue if no more question : )

**Comment by sabracewell** [comment]
Hi @DaliangNing I am wanting to use the RC.pc function on relative abundance data (values < 1) as per the original poster, but I am getting the same error message:

Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: invalid 'size' argument

I am using version 1.5.12. I tried running the function on the community dataframe created in step 9.5 as suggested above and still get the same error message. 

Was the issue solved for the original poster?

Hoping you can help, thanks.

**Comment by DaliangNing** [comment]
@sabracewell  please send me (ningdaliang@ou.edu) your R code and input files to debug.
