### ISSUE TITLE
Some questions about OTUs in each group

### ISSUE THREAD

**Issue by zhangy-zy775** [DaliangNing/iCAMP1#20]
Dear Ning:
  In my analysis,my treat file has juet one OTU in each group.When I use icamp package to calculate icamp.big,R will feedback error:

Error in `[.data.frame`(weight, (sig.phy > sig.phy.cut | sig.phy2 > sig.phy2.cut)) : 
  dims [product 2]与对象长度[11]不匹配

But when I add OTU to each group and make sure the number of OTUs in each gruop greater or eaqul to 2,the program can calculate smoothly.

Why is this happening?

**Comment by DaliangNing** [comment]
I am not sure what you mean by ‘treat file’.
In my code, “treat” is to specify the groups of samples rather than OTUs, like the example file ‘[treat2col.txt](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/treat2col.txt)’. I usually suggest each group has at least 6 samples.

**Comment by DaliangNing** [comment]
Has your problem been solved? If no more questions, I will close this issue soon.
