### ISSUE TITLE
Error in checkForRemoteErrors(val) :    2 nodes produced errors; first error: subscript out of bounds

### ISSUE THREAD

**Issue by YuZhang-learner** [DaliangNing/iCAMP1#25]
An error occurred before the updated version. 
When I updated to the latest version, I still had problems

`otu <- otu_table(ps_rs_filtered) %>% data.frame(.) %>% t() #row is sampleID
tax <- tax_table(ps_rs_filtered) %>% data.frame(.)
rand.time=1000  
nworker=30
memory.G=200
sampid.check=match.name(rn.list=list(otu=otu,treat=treat)) #Mismatch warning: treat.rowname has 24 mismatched names. 
treat=sampid.check$treat
otu=sampid.check$otu
otu=otu[,colSums(otu)>0,drop=FALSE] 
ncol(otu)# 32778
nrow(otu)# 72

spid.check=match.name(cn.list=list(otu=otu),rn.list=list(tax=tax),tree.list=list(tree=tree)) #Mismatch warning: tax.rowname has 45320 mismatched names. 
#The names are re-ranked.
Warning message:
In ape::drop.tip(tr, rm.tip) : drop all tips of the tree: returning NULL

otu=spid.check$otu
tax=spid.check$tax
tree=spid.check$tree

setwd(save.wd)
set.seed(12345)
if(!file.exists("pd.desc")) 
{
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker, memory.G = memory.G)
}else{
  pd.big=list()
  pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
  pd.big$pd.wd=save.wd
  pd.big$pd.file="pd.desc"
  pd.big$pd.name.file="pd.taxon.name.csv"
}

save(pd.big,file = "pd.big.rda")
save.image(file = "icamp.Rdata")

**#Now computing path. begin at Sun Jul 17 20:48:19 2022. Please wait...
Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: subscript out of bounds**

`

**Comment by jaimiewest** [comment]
I am also getting this error, at the same location with iCAMP::pdist.big

I just updated my R version...unsure if that has any effect because I never ran this code before the update.

**Comment by DaliangNing** [comment]
Please send me (ningdaliang@ou.edu) all your input files and R code to debug.

**Comment by YuZhang-learner** [comment]
@DaliangNing Thank you, I have solved the problem

**Comment by jaimiewest** [comment]
@YuZhang-learner How did you solve this problem?

**Comment by weiweiziyan** [comment]
@YuZhang-learner Hello, could you share the process that how did you solve the problem? Thank you!

**Comment by DaliangNing** [comment]
The previous error was probably due to mismatches of taxa IDs. If you still cannot figure out the solution to your problem, please send me (ningdaliang@ou.edu) your input files and R code to debug.
