### ISSUE TITLE
Error in h(simpleError(msg, call)) : when running  icamp.big

### ISSUE THREAD

**Issue by LuffyLuffy** [DaliangNing/iCAMP1#27]
----bMPD bin i=1 in 1 ---- Wed Nov 23 22:31:43 2022
Now calculating observed betaMPD. Begin at Wed Nov 23 22:31:43 2022. Please wait...
Now randomizing by parallel computing. Begin at Wed Nov 23 22:31:45 2022. Please wait...
Now fixing special cases. Begin at Wed Nov 23 22:31:53 2022. Please wait...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': subscript out of bounds

when using 
icamp.out <- icamp.big(comm = comm, tree = tree, 
                       pd.wd = getwd(), 
                       ses.cut = 1.96, 
                       rc.cut = 0.95, 
                       bin.size.limit = 5,
                       rand = 99, nworker = 4)

**Comment by DaliangNing** [comment]
Please send me (ningdaliang@ou.edu) your input files and R code to debug. BTW, for a real dataset, the bin.size.limit had better no less than 12 to get enough statistical power.

**Comment by DaliangNing** [comment]
I hope the problem has been solved. If no more questions, I will close this issue.

**Comment by zombiebride226** [comment]
Hello, I am very happy to see your post, and I am facing the same error but when calculating the iCAMP::qpen, may I know how you solved this problem? Thank you very much!

**Comment by zombiebride226** [comment]
Not exactly the same issue, it is shown in the following part:

qpout=iCAMP::qpen(comm=comm,pd=pd.big$pd.file,pd.big.wd=pd.big$pd.wd,
+                   pd.big.spname=pd.big$tip.label,ab.weight=TRUE,
+                   rand.time=rand.time, nworker=nworker,project=prefix,
+                   wd=save.wd, save.bNTIRC=TRUE)
The names are re-ranked.
All match very well.
All match very well.
Now calculating observed betaMNTD. Begin at Tue May 21 12:30:22 2024. Please wait...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': replacement has length zero
In addition: Warning messages:
1: 'memory.size()' is Windows-specific 
2: In FUN(if (length(d.call) < 2L) newX[, 1] else array(newX[, 1L],  :
  no non-missing arguments to min; returning Inf

**Comment by DaliangNing** [comment]
@zombiebride226 this looks like a format issue. You may send me (ningdaliang@ou.edu) your R code and input files to debug.

**Comment by zombiebride226** [comment]
> @zombiebride226 this looks like a format issue. You may send me ([ningdaliang@ou.edu](mailto:ningdaliang@ou.edu)) your R code and input files to debug.

Thanks a lot for your reply Prof. Ning! This has been solved after.
