### ISSUE TITLE
Solution to large dataset?

### ISSUE THREAD

**Issue by chenyj8** [DaliangNing/iCAMP1#28]
Hi Daliang,

My community composition matrix includes 1,000 samples x 550,000 OTUs. I ran the iCAMP analyses on a HPC with 94 CPUs and 470 Gb memory. However, an error message of out-of-memory occurs during the phylogenetic signal test and iCAMP::icamp.big.

Do you have any tips on such a large dataset?

Best,

Chen

**Comment by DaliangNing** [comment]
This is a big dataset. I got similar issue recently. I will check how i solved the problem and try to update package next week.

**Comment by DaliangNing** [comment]
Hope your problem is solved to some extent. If no more questions, I will close this issue soon.
