### ISSUE TITLE
missing values are not allowed with argument 'na.rm = FALSE'

### ISSUE THREAD

**Issue by liyangyang200112** [DaliangNing/iCAMP1#29]
Hi Daliang,
    When I run
# 9.5 # input community matrix as relative abundances (values < 1) rather than counts
comra=comm/rowSums(comm)
prefixra=paste0(prefix,"RA")
bin.size.limit = 24 # For real data, usually use a proper number according to phylogenetic signal test or try some settings then choose the reasonable stochasticity level. our experience is 12, or 24, or 48. but for this example dataset which is too small, have to use 5.
icres6=iCAMP::icamp.big(comm=comra,tree=tree,pd.desc=pd.big$pd.file, pd.spname=pd.big$tip.label, pd.wd=pd.big$pd.wd,
                        rand=rand.time,prefix=prefixra,ds=0.2,pd.cut=NA,sp.check=TRUE,
                        phylo.rand.scale="within.bin",taxa.rand.scale="across.all",
                        phylo.metric="bMPD",sig.index="Confidence",
                        bin.size.limit=bin.size.limit,nworker=nworker,memory.G=memory.G,
                        rtree.save=FALSE,detail.save=TRUE,qp.save=FALSE,detail.null=FALSE,
                        ignore.zero=TRUE,output.wd=save.wd,correct.special=TRUE,unit.sum=rowSums(comra),
                        special.method="depend",ses.cut = 1.96,rc.cut = 0.95,conf.cut=0.975,
                        omit.option="no",meta.ab=NULL, taxo.metric="bray", transform.method=NULL,
                        logbase=2, dirichlet=TRUE)

Error shows" 4 nodes produced errors; first error: missing values are not allowed with argument 'na.rm = false' "
How can I solve it? Thank you very much!

**Comment by DaliangNing** [comment]
Did you get this error when using the example dataset or your own dataset?  If it happens to your own dataset, please send me (ningdaliang@ou.edu) the input files and your R code for me to debug.

**Comment by Xiaojie0607** [comment]
Hi Professor Ning,

I also have the same problem as above when using my own dataset.  

When I run"9.5 # input community matrix as relative abundances (values < 1) rather than counts", error shows" 12nodes produced errors; first error: missing values are not allowed with argument 'na.rm = false' ".

I don't know what's wrong with the parameters or dataset. How can I solve it? Thank you very much!  

Best regards,

**Comment by DaliangNing** [comment]
Today's updated version (v1.6.2) may solve this problem. Please download version 1.6.2 or a later version from [https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions)

**Comment by DaliangNing** [comment]
I hope the problem has been solved. If no more questions, I will close this issue.
