### ISSUE TITLE
Values for ds and bin.size.limit

### ISSUE THREAD

**Issue by adityabandla** [DaliangNing/iCAMP1#3]
Hi Ning,

Thanks for the great package.  I went through your articles & the example code, however, I couldn't find how one can find optimal values for ds and bin.size.limit. Appreciate any advice/thoughts

On a related note, can categorical variables be used for identifying niche preferences i.e. used in the environment.txt file? We sampled across depth and as such depth integrates multiple niche dimensions, many of which we did not measure explicitly

Cheers, Adi

**Comment by adityabandla** [comment]
Figured it out myself, great explanations in the supplementary docs

**Comment by DaliangNing** [comment]
ds can be determined by phylogenetic signal analysis as Stegen et al 2013 (Fig.2 in doi:10.1038/ismej.2013.93) and Wang et al 2013 (Fig.1 in doi:10.1038/ismej.2013.30). From the previous publications and my test with simulated data, ds=0.2 seems a generally acceptable choice.

bin.size.limit is more tricky. In our paper (doi:10.1038/s41467-020-18560-z), I suggested two ways to determine the bin.size.limit: one is based on phylogenetic signal within bin (Supplementary Fig.4 in the paper; Step 7 and 8 in the [example code](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r)); the other is based on stochasticity estimated by NST (https://github.com/DaliangNing/NST), and you may try several values (e.g. 12, 24, 48) of bin.size.limit and use the one making the relative importance of stochastic processes (dispersal + drift) closer to NST.

Current niche preference calculation needs numeric environmental factors. A categorical factor is not applicable.

**Comment by adityabandla** [comment]
Thanks, Ning! much appreciated

**Comment by yjiakang** [comment]
@DaliangNing Hi, how can I determine the optimal bin.size.limit without environmental file? There are 4904 ASVs in the community. Can I just use 24?

**Comment by yjiakang** [comment]
Hi, meanwhile, the icamp.boot help indicates that **Observed: the mean relative importance of each process in each group** in the file `iCAMP.BootSummary.Group`. Then what is the difference between Observed and Mean? They have different values. Which one should I choose when presenting the percentage of processes in one group? Many thanks in advance and hoping for your reply.

**Comment by DaliangNing** [comment]
> Hi, meanwhile, the icamp.boot help indicates that **Observed: the mean relative importance of each process in each group** in the file `iCAMP.BootSummary.Group`. Then what is the difference between Observed and Mean? They have different values. Which one should I choose when presenting the percentage of processes in one group? Many thanks in advance and hoping for your reply.

"Observed“ was calculated using all the samples. 'Mean' is the mean of bootstrapping results; bootstrapping randomly draws samples with replacement (thus mostly a subset of samples each time) for 1000 times, to get the 1000 bootstrapping results. Therefore, 'Observed' is preferred. But if 'Observed' shows a large difference from the 1000 bootstrapping results, it is possibly due to the original samples have some obvious outlier(s); you may need to consider excluding non-representative sample(s) and redo iCAMP. In some cases, the large difference between 'observed' and bootstrapping results may be due to too few samples (no enough statistical power), then, bootstrapping may not be applicable to the dataset.

**Comment by DaliangNing** [comment]
> [@DaliangNing](https://github.com/DaliangNing) Hi, how can I determine the optimal bin.size.limit without environmental file? There are 4904 ASVs in the community. Can I just use 24?

sometimes, geographic coordinates, temperature, or even treatments can be served as enviornmental factors as they could represent environmental conditions. 
If environmental factors are not available in any way, you may assess the average stochasticity level of your data using NST (https://github.com/DaliangNing/NST/), then select the bin.size.limit making the average of the sum of 'Dispersal + Drift' the closest to the average NST, as iCAMP regards dispersal and drift as stochastic processes, and their sum should be close to the stochasticity assessed by NST.

**Comment by yjiakang** [comment]
> > Hi, meanwhile, the icamp.boot help indicates that **Observed: the mean relative importance of each process in each group** in the file `iCAMP.BootSummary.Group`. Then what is the difference between Observed and Mean? They have different values. Which one should I choose when presenting the percentage of processes in one group? Many thanks in advance and hoping for your reply.
> 
> "Observed“ was calculated using all the samples. 'Mean' is the mean of bootstrapping results; bootstrapping randomly draws samples with replacement (thus mostly a subset of samples each time) for 1000 times, to get the 1000 bootstrapping results. Therefore, 'Observed' is preferred. But if 'Observed' shows a large difference from the 1000 bootstrapping results, it is possibly due to the original samples have some obvious outlier(s); you may need to consider excluding non-representative sample(s) and redo iCAMP. In some cases, the large difference between 'observed' and bootstrapping results may be due to too few samples (no enough statistical power), then, bootstrapping may not be applicable to the dataset.

Thanks for your quick reply. According to your explanation, I guess the **_Stdev_** in the file `iCAMP.BootSummary.Group` is from bootstrapping results rather than from the samples in one group. Then what if I want to draw a figure like Fig. 3C in you Nat Comm paper, where should the stdev from samples in one group be obtained?

**Comment by yjiakang** [comment]
> > [@DaliangNing](https://github.com/DaliangNing) Hi, how can I determine the optimal bin.size.limit without environmental file? There are 4904 ASVs in the community. Can I just use 24?
> 
> sometimes, geographic coordinates, temperature, or even treatments can be served as enviornmental factors as they could represent environmental conditions. If environmental factors are not available in any way, you may assess the average stochasticity level of your data using NST (https://github.com/DaliangNing/NST/), then select the bin.size.limit making the average of the sum of 'Dispersal + Drift' the closest to the average NST, as iCAMP regards dispersal and drift as stochastic processes, and their sum should be close to the stochasticity assessed by NST.

I tried by using treatment file, however, 
`> niche.dif=iCAMP::dniche(env = env,comm = comm,method = "niche.value",
+                         nworker = nworker,out.dist=FALSE,bigmemo=TRUE,
+                         nd.wd=save.wd)
All match very well.
Error in as.matrix(comts) %*% as.matrix(env) : 
  requires numeric/complex matrix/vector arguments`
I guess category type is not supported as env file.

**Comment by DaliangNing** [comment]
You need to change the treatment information table to a numeric matrix. If the treatment only has two levels (e.g., control vs treatment), you can set one level as 0, the other level as 1. If the treatment has multiple levels: if you can rank the differnt levels, you can use numbers to replace the levels, e.g., high, medium, low intensity groups, can be changed to 3, 2, 1; if you can not rank the levels, you need to use dummy vectors, e.g., 3-type management X, Y, Z,  sample A, B, C, D are under X, X, Y, Z, respectivly, you can transform the treatment to two columns (variables), one is Management.X, values in sample A, B, C, D are 1, 1, 0, 0; the other is Management.Y, values in sample A-D are 0, 0, 1, 0; Management.Z=[0,0,0,1] is redundant, no need to add.

**Comment by DaliangNing** [comment]
> > > Hi, meanwhile, the icamp.boot help indicates that **Observed: the mean relative importance of each process in each group** in the file `iCAMP.BootSummary.Group`. Then what is the difference between Observed and Mean? They have different values. Which one should I choose when presenting the percentage of processes in one group? Many thanks in advance and hoping for your reply.
> > 
> > 
> > "Observed“ was calculated using all the samples. 'Mean' is the mean of bootstrapping results; bootstrapping randomly draws samples with replacement (thus mostly a subset of samples each time) for 1000 times, to get the 1000 bootstrapping results. Therefore, 'Observed' is preferred. But if 'Observed' shows a large difference from the 1000 bootstrapping results, it is possibly due to the original samples have some obvious outlier(s); you may need to consider excluding non-representative sample(s) and redo iCAMP. In some cases, the large difference between 'observed' and bootstrapping results may be due to too few samples (no enough statistical power), then, bootstrapping may not be applicable to the dataset.
> 
> Thanks for your quick reply. According to your explanation, I guess the **_Stdev_** in the file `iCAMP.BootSummary.Group` is from bootstrapping results rather than from the samples in one group. Then what if I want to draw a figure like Fig. 3C in you Nat Comm paper, where should the stdev from samples in one group be obtained?

In that paper, I used the pairwise NSTij within each group to get the standard deviation rather than the Stdev from icamp.boot results. But it is more recommended to use a box plot, showing the variation of bootstrapping results, and add dots or triangle symbols upon the box plot to show 'observed' values.

**Comment by yjiakang** [comment]
@DaliangNing Thanks for your patience and reply.

**Comment by yjiakang** [comment]
Is the sum of **'Dispersal + Drift' =** `Dispersal Limitation + Homogenizing Dispersal + Drift.and.Others = Stochasticity` in the iCAMP.BootSummary.Group file?

**Comment by DaliangNing** [comment]
> Is the sum of **'Dispersal + Drift' =** `Dispersal Limitation + Homogenizing Dispersal + Drift.and.Others = Stochasticity` in the iCAMP.BootSummary.Group file?

Yes.
