### ISSUE TITLE
X nodes produced errors; first error: 'size'参数不对

### ISSUE THREAD

**Issue by Zhenghong-Wang** [DaliangNing/iCAMP1#31]
Dear author, when I use the code of iCMAP ，the error occurred: 
“ icamp.out=icamp.big(comm=comm,tree=tree,#pd.wd=pd.wd,
+                     rand=999, nworker=4,bin.size.limit=12,ds=0.2)
The names are re-ranked.
----------Now binning-----------------Sun Feb 12 16:12:40 2023
Now computing path. begin at Sun Feb 12 16:12:40 2023. Please wait...
Now computing path. begin at Sun Feb 12 16:12:44 2023. Please wait...
Now computing dist to root. begin at Sun Feb 12 16:12:45 2023. Please wait...
----------Now binning com and sp without omitting small bins-----------------Sun Feb 12 16:12:47 2023
----bMPD bin i=1 in 37 ---- Sun Feb 12 16:12:48 2023
Now calculating observed betaMPD. Begin at Sun Feb 12 16:12:48 2023. Please wait...
Now randomizing by parallel computing. Begin at Sun Feb 12 16:12:48 2023. Please wait...
Now fixing special cases. Begin at Sun Feb 12 16:13:07 2023. Please wait...
All match very well.
Now calculating observed MPD. Begin at Sun Feb 12 16:13:12 2023. Please wait...
Now randomizing by parallel computing. Begin at Sun Feb 12 16:13:12 2023. Please wait...
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: 'size'参数不对
此外: There were 11 warnings (use warnings() to see them) ”

I don't know wha't wrong with the parameters, my data have same formation with example data, and I already adjusted the  parameter but the issue not addressed.Do you have any suggestions?

**Comment by DaliangNing** [comment]
Please send me (ningdaliang@ou.edu) your R code and input file(s). I will try to debug.

**Comment by Zhenghong-Wang** [comment]
Dear professor Ning,


Hope everthing is going well with you.
Many thinks for your reply and I am very happy to receive your message. Attached is my code and data.
At first time I see the error, I think may be the problem from formation(name , and dataset size),and the 0 abundance OTU column existence,but neither. So I don't know what's wrong with it. Expect you reply soon.


Best regards,
Zhenghong 













--



王正洪 (Zhenghong Wang)

南方科技大学生物系

广东省深圳市南山区学苑大道1088号




At 2023-02-17 09:03:18, "Daliang Ning" ***@***.***> wrote:

Please send me ***@***.***) your R code and input file(s). I will try to debug.

**Comment by DaliangNing** [comment]
Strangely, I did not see any attached code or file. Could you send me again?

**Comment by Zhenghong-Wang** [comment]
Dear professor Ning,


Sorry to this bug, may something wrong during the internet. Please chect it agai. So I don't know what's wrong with it. Expect you reply soon.


Best regards,
Zhenghong 







--



王正洪 (Zhenghong Wang)

南方科技大学生物系

广东省深圳市南山区学苑大道1088号




At 2023-02-17 09:03:18, "Daliang Ning" ***@***.***> wrote:

Please send me ***@***.***) your R code and input file(s). I will try to debug.

**Comment by DaliangNing** [comment]
Looks like it is difficult to get attachments to GitHub when you just reply email to GitHub message. You may directly send files to my email address ningdaliang@ou.edu.

**Comment by DaliangNing** [comment]
I suggest you use the updated example code to perform iCAMP.
[https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r)

One special issue in your data is that the values in your ASV table are all decimals rather than counts (integers). iCAMP works best with integer data (e.g., rarefied ASV table). You may try one of the following two options:
(1) divided the whole table with the minimal positive value, then round all numbers to the nearest integers. 
(2) If there are good reasons to use decimals, you may calculate the relative abundance for each ASV in each sample (so the sum of each sample is one), then set dirichlet=TRUE in icamp.big.

**Comment by DaliangNing** [comment]
Hope your problem is solved. If no more questions, I will close this issue soon.

**Comment by Zhenghong-Wang** [comment]
Hi Professor Ning, 
I apologize for my delayed response. For my issue, I subsequently calculated it using the raup_crick_abundance function. This is relatively more cumbersome compared to using iCAMP. Anyway, I will try your suggestions when I have the opportunity later. Thank you once again for your response. I also appreciate your contributions to the field of community ecology, and I wish you continued success in your future endeavors.
best regards,
Zhenghong













--



王正洪 (Zhenghong Wang)

南方科技大学生物系

广东省深圳市南山区学苑大道1088号




At 2023-09-05 06:59:16, "Daliang Ning" ***@***.***> wrote:

I suggest you use the updated example code to perform iCAMP.
https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r

One special issue in your data is that the values in your ASV table are all decimals rather than counts (integers). iCAMP works best with integer data (e.g., rarefied ASV table). You may try one of the following two options:
(1) divided the whole table with the minimal positive value, then round all numbers to the nearest integers.
(2) If there are good reasons to use decimals, you may calculate the relative abundance for each ASV in each sample (so the sum of each sample is one), then set dirichlet=TRUE in icamp.big.
