### ISSUE TITLE
Error in oldname[j, 1:2] : subscript out of bounds

### ISSUE THREAD

**Issue by Xiaojie0607** [DaliangNing/iCAMP1#33]
Dear professor Ning,

Hope everthing is going well with you.

when I run ，the error occurred:
"> icbin=iCAMP::icamp.bins(icamp.detail = icres$detail,treat = treat,
+                  clas=clas,silent=FALSE, boot = TRUE,
+                  rand.time = rand.time,between.group = TRUE)
Now summarizing method=CbMPDiCbraya i=1 j=1. Mon Feb 27 21:43:00 2023
bootstrapping rt=1. Mon Feb 27 21:43:00 2023
bootstrapping rt=201. Mon Feb 27 21:43:01 2023
bootstrapping rt=401. Mon Feb 27 21:43:02 2023
bootstrapping rt=601. Mon Feb 27 21:43:03 2023
bootstrapping rt=801. Mon Feb 27 21:43:04 2023
Now summarizing method=CbMPDiCbraya i=1 for between.group j=1 v=2. Mon Feb 27 21:43:05 2023
Error in oldname[j, 1:2] : subscript out of bounds"

I don't know wha't wrong with it. Do you have any suggestions? Thank you very much!

Best regards,

xiaojie

**Comment by DaliangNing** [comment]
It looks like there is only one treatment in 'treat' table. If so, 'between.group = TRUE' will not work. You may set 'between.group = FALSE'.

**Comment by Xiaojie0607** [comment]
Dear professor Ning,

Hope everthing is going well with you.

The problem has been solved based on your suggestion! Thank you very much!

Best regards,

xiaojie

**Comment by DaliangNing** [comment]
my pleasure. I am closing the issue.

**Comment by huizhen-yan** [comment]
Dear Prof. Ning,
        I also got the same error even though I set 'between.group=FALSE, 
![image](https://user-images.githubusercontent.com/71927771/236989268-2ae661a9-8d56-4363-a67e-263a95a9a1c8.png)
        I have checked my treat file and found that there are 9 groups (treatment), each containing at least 4 samples. Could you please tell me what could be the reason for the error?
 Thank you in advance.

**Comment by DaliangNing** [comment]
If the problem has not been solved yet, please send me (ningdaliang@ou.edu) your input files and R code to debug.

**Comment by huizhen-yan** [comment]
宁老师：

您好！

谢谢您的回复。我的问题 (issue38)目前还没解决，输入文件和所用代码附上。

Summer是在第八步使用taxa.binphy.big()函数计算系统发育信号时出现图中问题的数据集；Autumn是在这步运行正常的数据集。

我个人测试的结果是可能与进化树的结构有关，在taxa.binphy.big()要求使用有根树，于是我使用脚本make_phylogeny.py -i otus.aln.trimal -r midpoint -o otus-rootqiime1.tre创建了有根树。在第九步icamp.big()主函数计算所有bins的构建过程这步并不要求进化树是否有根，于是我分别运行了基于有根树和无根树的icamp.big()，发现设置同样的参数（ds = 0.2, bin.size.limit = 5）划分得到的bins数量相差非常大，例如对于Autumn数据集，基于无根树的bins数量为673个，基于有根树的bins数量超过3000个。

系统发育信号的计算是基于系统发育距离和生态位距离，相对距离即可，所以我的理解是不是不必要限制有根树。

&nbsp;

闫慧贞

2023年7月6日星期四





闫慧贞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DaliangNing/iCAMP1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 上午6:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DaliangNing/iCAMP1] Error in oldname[j, 1:2] : subscript out of bounds (Issue #33)





 
If the problem has not been solved yet, please send me ***@***.***) your input files and R code to debug.

**Comment by DaliangNing** [comment]
I did not see any attachments. please send the files to my OU email address (ningdaliang@ou.edu).

For real dataset, bin.size.limit needs to be determined by phylogenetic signal test or based on stochasticity level assessed by NST. generally it is much higher than 5, e.g., 24 or 48.

In my experience, midpoint rooted tree is the best for iCAMP analysis. other types of trees can lead to strange results.
