### ISSUE TITLE
Can't find the help documents

### ISSUE THREAD

**Issue by Joshcole2504** [DaliangNing/iCAMP1#34]
Hi,

Really sorry as I'm sure I am missing something very obvious - but I can't find the help documents. For example, in 8.2 it says '# see help document of the function "ps.bin" for the meaning of output' and in step 9 it says 'ig.index="Confidence" # see other options in help document of icamp.big'. 

Would you be able to point me in the direction of the help documents.

Thanks,
Josh

**Comment by DaliangNing** [comment]
In R, after install iCAMP package and load it with 'library(iCAMP)', you can use '?ps.bin' to get the help document.

If you search 'R iCAMP ps.bin' in google, you may also see the help document, e.g., [https://rdrr.io/cran/iCAMP/man/ps.bin.html](https://rdrr.io/cran/iCAMP/man/ps.bin.html)
