### ISSUE TITLE
Error shows" Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: subscript out of bounds"

### ISSUE THREAD

**Issue by Xiaojie0607** [DaliangNing/iCAMP1#35]
Hi Professor Ning,
When I run "# 6 # calculate pairwise phylogenetic distance matrix.":
 # since microbial community data usually has a large number of species (OTUs or ASVs), we use "big.matrix" in R package "bigmemory" to handle the large phylogenetic distance matrix. 
> setwd(save.wd)
> if(!file.exists("pd.desc")) 
+ {
+   pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker, memory.G = memory.G)
+   # output files:
+   # path.rda: a R object to list all the nodes and  edge lengthes from root to every tip. saved in R data format. an intermediate output when claculating phylogenetic distance matrix.
+   # pd.bin: BIN file (backingfile) generated by function big.matrix in R package bigmemory. This is the big matrix storing pairwise phylogenetic distance values. By using this bigmemory format file, we will not need memory but hard disk when calling big matrix for calculation.
+   # pd.desc: the DESC file (descriptorfile) to hold the backingfile (pd.bin) description.
+   # pd.taxon.name.csv: comma delimited csv file storing the IDs of tree tips (OTUs), serving as the row/column names of the big phylogenetic distance matrix.
+ }else{
+   # if you already calculated the phylogenetic distance matrix in a previous run
+   pd.big=list()
+   pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
+   pd.big$pd.wd=save.wd
+   pd.big$pd.file="pd.desc"
+   pd.big$pd.name.file="pd.taxon.name.csv"
+ }
Now computing path. begin at Wed Mar  8 13:12:29 2023. Please wait...
Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: subscript out of bounds
In addition: Warning message:
'memory.limit()' is no longer supported 

Error shows" Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: subscript out of bounds"

I don't know what's wrong with the parameters.  How can I solve it? Thank you very much! 

Best regards,

Xiaojie

[category.txt](https://github.com/DaliangNing/iCAMP1/files/10917480/category.txt)
[classification.txt](https://github.com/DaliangNing/iCAMP1/files/10917481/classification.txt)
[otus.txt](https://github.com/DaliangNing/iCAMP1/files/10917482/otus.txt)
[treat2col.txt](https://github.com/DaliangNing/iCAMP1/files/10917485/treat2col.txt)

**Comment by CHRISoSHAO** [comment]
你好，请问这个问题有好的办法解决么，我也同样遇到了这个问题

**Comment by DaliangNing** [comment]
It is usually caused by file format or tree quality. You can send me (ningdaliang@ou.edu) your input files and R code to debug.

**Comment by gaoyue23** [comment]
你好，请问解决了嘛，今天我也遇到同样的问题了

**Comment by DaliangNing** [comment]
This type of errors can be caused by various reasons, mostly related to file format or tree quality. You can send me ([ningdaliang@ou.edu](mailto:ningdaliang@ou.edu)) your input files and R code to debug.

**Comment by shijiamian1998** [comment]
你好，请问解决了吗，我在计算βNTI的时候也遇到了同样的问题，但用的不是这个包

**Comment by gaoyue23** [comment]
现在解决了




| |
高悦
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/13/2024 18:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [DaliangNing/iCAMP1] Error shows" Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: subscript out of bounds" (Issue #35) |

你好，请问解决了吗，我在计算βNTI的时候也遇到了同样的问题，但用的不是这个包

**Comment by shijiamian1998** [comment]
> 现在解决了 | | 高悦 | | @***.*** | ----回复了消息 ---- |从 |@***.***> | |日期 |2024-4-13 18：06 | |至 |@***.***> | |抄送 |@***.***> , @***.***> | |主题 |回复：[DaliangNing/iCAMP1] 错误显示“ checkForRemoteErrors（val） 中的错误：2 个节点产生错误;第一个错误：下标越界“（问题 #35） | 你好，请问解决了吗，我在计算βNTI的时候也遇到了同样的问题，但用的不是这个包 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

您好，方便问一下是怎么解决的吗，是什么原因导致的这个报错呢？非常感谢您的回复！

**Comment by gaoyue23** [comment]
这个是数据的问题，你把没有注释到的，NA的值删掉就可以了。


| |
高悦
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/15/2024 19:14 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [DaliangNing/iCAMP1] Error shows" Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: subscript out of bounds" (Issue #35) |

现在解决了 | | 高悦 | | @. | ----回复了消息 ---- |从 ***@***.***> | |日期 |2024-4-13 18：06 | |至 ***@***.***> | |抄送 ***@***.***> , @.> | |主题 |回复：[DaliangNing/iCAMP1] 错误显示“ checkForRemoteErrors（val） 中的错误：2 个节点产生错误;第一个错误：下标越界“（问题 #35） | 你好，请问解决了吗，我在计算βNTI的时候也遇到了同样的问题，但用的不是这个包 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ***@***.******>

您好，方便问一下是怎么解决的吗，是什么原因导致的这个报错呢？非常感谢您的回复！

**Comment by DaliangNing** [comment]
@shijiamian1998  Sorry, I got too busy to respond in time recently. If your problem has not been solved yet, you may send me (ningdaliang@ou.edu) your input files and R code to debug.
