### ISSUE TITLE
Dealing with dataset with four metacommunities

### ISSUE THREAD

**Issue by adityabandla** [DaliangNing/iCAMP1#37]
Hi Ning,

How would you suggest using iCAMP to deal with a dataset comprising groups of samples from four different metacommunities? The group comparisons within each metacommunity is the same, just that I would like to treat the turnovers within each one separately and then compare them at the end. Thanks for your time

Regards, Adi

**Comment by adityabandla** [comment]
@DaliangNing I see this is already implemented in the function `qpen.cm`. Can a similar thing be implemented for `icamp.big`?

**Comment by DaliangNing** [comment]
Please use the function icamp.cm, which was included in iCAMP after version 1.5.2.
icamp.cm example is in step 9.3.2 of iCAMP example code: [https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r)
The latest version (v 1.6.2) can be downloaded from GitHub: [https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions)
