### ISSUE TITLE
Error in GetElements.bm(x, i, j): Illegal row index usage in extraction

### ISSUE THREAD

**Issue by huizhen-yan** [DaliangNing/iCAMP1#38]
Hi,
I got the following error when doing phylogenetic binning. 
<img width="676" alt="image" src="https://github.com/DaliangNing/iCAMP1/assets/71927771/be1e1f78-b184-46d3-baeb-6786b1e296d9">

The data run normally for the other three seasons, but this error occurred during the summer. How to resolve it?

**Comment by DaliangNing** [comment]
you may send me (ningdaliang@ou.edu) the input files and R code to debug.

**Comment by DaliangNing** [comment]
I recommend using midpoint root before taxa.binphy.big.
`
tree.rt=iCAMP::midpoint.root.big(tree = tree, pd.desc = pd.big$pd.file,
                                   pd.spname = pd.big$tip.label,pd.wd = pd.big$pd.wd,
                                   nworker = nworker)
tree=tree.rt$tree
`

In addition, a real microbial dataset had better use bin.size.limit no less than 12.

**Comment by DaliangNing** [comment]
Hope your problem is solved. If no more questions, I will close this issue soon.
