### ISSUE TITLE
Issue with Cluster on R4.03 MacOS Big Sur

### ISSUE THREAD

**Issue by bholt20** [DaliangNing/iCAMP1#4]
This package ran excellently on a previous version of R, but after updating to 4.03 and reinstalling packages, I am now getting the following error:

Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 4 of 4 workers failed to connect.

I tried saw on a different page this issue can be resolved by specifying clusters:
parallel::makeCluster(4, setup_strategy = "sequential")

But this did not seem to work for me.

Thanks!

**Comment by DaliangNing** [comment]
Sorry to hear that. I searched around. This seems a difficult problem without a final solution yet.
https://github.com/rstudio/rstudio/issues/6692

I do not have Mac, thus, cannot test. If you find any solution, I am willing to revise iCAMP.
If you are using Rstudio, did you try the original R?
If R 4.x does not work anyway, you may have to install an old version of R (>=3.5) to run iCAMP, until R or the 'parallel' package developers find the solution.
If your dataset is not very large, you may use our galaxy pipeline [http://ieg3.rccc.ou.edu:8080/](http://ieg3.rccc.ou.edu:8080/). please email me (ningdaliang@ou.edu) to set up your account.

**Comment by bholt20** [comment]
I believe I have found a temporary fix: 
cl <- parallel::makeCluster(10, setup_timeout = 0.5)

Then specify nworkers= cl and it seemed to work for me. For others having this issue, try some of the other solutions on the above link if this doesn't work.

Thanks!

**Comment by DaliangNing** [comment]
Great. I will try to add this to the functions.

**Comment by DaliangNing** [comment]
The following code has been added to iCAMP (version >=  1.4.3, can be found in [/RPckage/AllVersion](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions)).

paste0("RC",taxo.metric,"                            i")
Example output files


c1<-try(parallel::makeCluster(nworker,type="PSOCK"))
if(class(c1)[1]=='try-error'){c1 <- parallel::makeCluster(nworker, setup_timeout = 0.5)}
if(class(c1)[1]=='try-error'){c1 <- parallel::makeCluster(nworker, setup_strategy = "sequential")}

**Comment by DaliangNing** [comment]
@bholt20 please let me know if the new version (1.4.3) can solve your problem. I will close this issue if no more question : )

**Comment by bholt20** [comment]
Yes, this fixed it. Thanks!
