### ISSUE TITLE
Error in serialize(data, node$con) : ignoring SIGPIPE signal

### ISSUE THREAD

**Issue by hahamark-learn** [DaliangNing/iCAMP1#41]
hello, I get the same error. I check the node number in the tree, the number isn't abnormally low compared to the tip number.

the code like this 

----bMPD bin i=15 in 435 ---- Tue Aug  1 21:42:18 2023
Now calculating observed betaMPD. Begin at Tue Aug  1 21:42:18 2023. Please wait...
Now randomizing by parallel computing. Begin at Tue Aug  1 21:43:31 2023. Please wait...
Now fixing special cases. Begin at Tue Aug  1 21:44:54 2023. Please wait...
All match very well.
Now calculating observed MPD. Begin at Tue Aug  1 21:44:55 2023. Please wait...
Error in makePSOCKcluster(names = spec, ...) :
  Cluster setup failed. 15 of 15 workers failed to connect.
Error in makePSOCKcluster(names = spec, ...) :
  Cluster setup failed. 14 of 15 workers failed to connect.
Now randomizing by parallel computing. Begin at Tue Aug  1 21:47:54 2023. Please wait...
Error in serialize(data, node$con) : ignoring SIGPIPE signal

Can you give me some advices?

**Comment by hahamark-learn** [comment]
otu <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\16s-otu.csv",row.names = 1,header = T)
comm <- t(otu)
tree <- read.tree("C:\\Users\\DELL\\Desktop\\Abundant\\16s-fasttree")
class <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\16s-class.csv",row.names = 1,header = T,sep = "\t")
treat <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\site-group",sep="\t",row.names = 1,header = T)
save.wd=("C:\\Users\\DELL\\Desktop\\Abundant\\") # please change to the folder you want to save the pd.big output.
nworker=20 # parallel computing thread number
rand.time=10 # usually use 1000 for real data.
bin.size.limit=48

setwd(save.wd)
if(!file.exists("pd.desc")) {
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker)
  # output files:
  # path.rda: a R object to list all the nodes and  edge lengthes from root to every tip. saved in R data format. an intermediate output when claculating phylogenetic distance matrix.
  # pd.bin: BIN file (backingfile) generated by function big.matrix in R package bigmemory. This is the big matrix storing pairwise phylogenetic distance values. By using this bigmemory format file, we will not need memory but hard disk when calling big matrix for calculation.
  # pd.desc: the DESC file (descriptorfile) to hold the backingfile (pd.bin) description.
  # pd.taxon.name.csv: comma delimited csv file storing the IDs of tree tips (OTUs), serving as the row/column names of the big phylogenetic distance matrix.
}else{
  # if you already calculated the phylogenetic distance matrix in a previous run
  pd.big=list()
  pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
  pd.big$pd.wd=save.wd
  pd.big$pd.file="pd.desc"
  pd.big$pd.name.file="pd.taxon.name.csv"
}

icamp.out=iCAMP::icamp.big(comm=comm,tree=tree,pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label,
                           pd.wd = pd.big$pd.wd,
                           rand=rand.time, nworker=nworker,
                           bin.size.limit=bin.size.limit,
                           sig.index = "SES.RC",phylo.metric ="bNRI")

**Comment by hahamark-learn** [comment]
`otu <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\16s-otu.csv",row.names = 1,header = T)
comm <- t(otu)
tree <- read.tree("C:\\Users\\DELL\\Desktop\\Abundant\\16s-fasttree")
class <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\16s-class.csv",row.names = 1,header = T,sep = "\t")
treat <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\site-group",sep="\t",row.names = 1,header = T)
save.wd=("C:\\Users\\DELL\\Desktop\\Abundant\\") # please change to the folder you want to save the pd.big output.
nworker=20 # parallel computing thread number
rand.time=10 # usually use 1000 for real data.
bin.size.limit=40


setwd(save.wd)
if(!file.exists("pd.desc")) {
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker)
  # output files:
  # path.rda: a R object to list all the nodes and  edge lengthes from root to every tip. saved in R data format. an intermediate output when claculating phylogenetic distance matrix.
  # pd.bin: BIN file (backingfile) generated by function big.matrix in R package bigmemory. This is the big matrix storing pairwise phylogenetic distance values. By using this bigmemory format file, we will not need memory but hard disk when calling big matrix for calculation.
  # pd.desc: the DESC file (descriptorfile) to hold the backingfile (pd.bin) description.
  # pd.taxon.name.csv: comma delimited csv file storing the IDs of tree tips (OTUs), serving as the row/column names of the big phylogenetic distance matrix.
}else{
  # if you already calculated the phylogenetic distance matrix in a previous run
  pd.big=list()
  pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
  pd.big$pd.wd=save.wd
  pd.big$pd.file="pd.desc"
  pd.big$pd.name.file="pd.taxon.name.csv"
}






icamp.out=iCAMP::icamp.big(comm=comm,tree=tree,pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label,
                           pd.wd = pd.big$pd.wd,
                           rand=rand.time, nworker=nworker,
                           bin.size.limit=bin.size.limit,
                           sig.index = "SES.RC",phylo.metric ="bNRI")`

**Comment by hahamark-learn** [comment]
otu <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\16s-otu.csv",row.names = 1,header = T)
comm <- t(otu)
tree <- read.tree("C:\\Users\\DELL\\Desktop\\Abundant\\16s-fasttree")
class <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\16s-class.csv",row.names = 1,header = T,sep = "\t")
treat <- read.csv("C:\\Users\\DELL\\Desktop\\Abundant\\site-group",sep="\t",row.names = 1,header = T)
save.wd=("C:\\Users\\DELL\\Desktop\\Abundant\\") # please change to the folder you want to save the pd.big output.
nworker=20 # parallel computing thread number
rand.time=10 # usually use 1000 for real data.
bin.size.limit=40
setwd(save.wd)
if(!file.exists("pd.desc")) {
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker)
}else{
  pd.big=list()
  pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
  pd.big$pd.wd=save.wd
  pd.big$pd.file="pd.desc"
  pd.big$pd.name.file="pd.taxon.name.csv"
}
icamp.out=iCAMP::icamp.big(comm=comm,tree=tree,pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label,
                           pd.wd = pd.big$pd.wd,
                           rand=rand.time, nworker=nworker,
                           bin.size.limit=bin.size.limit,
                           sig.index = "SES.RC",phylo.metric ="bNRI")

**Comment by DaliangNing** [comment]
Please send me (ningdaliang@ou.edu) your input files to debug.

**Comment by hahamark-learn** [comment]
i sent the raw data to you, please check it.

**Comment by DaliangNing** [comment]
I am testing your data with the code below and the latest version of iCAMP (v1.6.4, available in [https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions)). Till now, it is running bNRI in the 141st bin in 317 bins; no error yet. 

R code:
[https://github.com/DaliangNing/iCAMP1/blob/master/Examples/Debug/20230908.YL.icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/Debug/20230908.YL.icamp.test.r)

Some notes:
(1) Your OTU table has different sequence numbers in different samples. We usually rarefy all samples to the same sequence number. If your research requires to use OTU table without rarefaction, please skip the step 3.2 below. 
(2) rand.time is set as 20 for a quick test. Generally, use 1000. If too time-consuming, 200 may be acceptable.
(3) Please check the example code for more options and steps [https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r)

**Comment by DaliangNing** [comment]
Hope your problem is solved. If no more questions, I will close this issue soon.
