### ISSUE TITLE
How to get the results of each ecological process of each bin between each two samples

### ISSUE THREAD

**Issue by Ryeguyuzheng** [DaliangNing/iCAMP1#42]
Hi,

I tried to find an output about the each ecological process of each bin between each two samples but failed. I found the results of the file named icbin$Wtuvk turned out to be pretty much what I was looking for, but they only showed the names of dominant process, not the detailed values. Does the output exist to get what I want? If not, how do I calculate to get them.

Sincerely

**Comment by DaliangNing** [comment]
Down to the turnover of each bin between two specific samples, iCAMP can only give qualitative results, i.e., dominant ecological process, but not a percentage.

**Comment by DaliangNing** [comment]
Hope your question is addressed. If no more questions, I will close this issue soon.

**Comment by Ryeguyuzheng** [comment]
Thank you for your response! My question is addressed.
