### ISSUE TITLE
Hi, professor Ning, I would like to ask you about the operation of iCAMP code

### ISSUE THREAD

**Issue by Jia2023888** [DaliangNing/iCAMP1#45]
When I run the line of code: ieggr::save.file(t(comm),filename = "16s-otu.resamp")
there is an error: **Error in library(ieggr) : 不存在叫‘ieggr’这个名字的程辑包**

I have tried changed the version of R and installed the package in a variety of ways, but all falied. It seems there is no file of the package ieggr in github or other website. I would very appreciate it if you could provide me with the local files of package "ieggr" .

**Comment by DaliangNing** [comment]
ieggr is our internal package, not published yet. You may use 'write.csv' or 'write.table' in R to save the file.
