### ISSUE TITLE
The issue with step"binps=iCAMP::ps.bin"

### ISSUE THREAD

**Issue by linxuanhuogatech** [DaliangNing/iCAMP1#46]
Hello Daliang, l followed the script, and when l ran this part : 
"binps=iCAMP::ps.bin(sp.bin = sp.bin,sp.ra = sp.ra,
                    spname.use = spname.use,
                    pd.desc = pd.big$pd.file, pd.spname = pd.big$tip.label, pd.wd = pd.big$pd.wd,
                    nd.list = niche.dif$nd,nd.spname = nd.spname,ndbig.wd = niche.dif$nd.wd,
                    cor.method = "kendall",r.cut = 0.1, p.cut = 0.05, min.spn = 10)

The error message is "Error in cor(as.vector(xdis), ydis, method = method, use = use) : 
  missing observations in cov/cor" 

How could i fix this?

**Comment by DaliangNing** [comment]
Looks like your environmental table may have missing data. Please send me (ningdaliang@ou.edu) your input files and R code to debug.

**Comment by DaliangNing** [comment]
I hope your problem has been solved. If no more questions, I will close this issue soon.
