### ISSUE TITLE
Error in UseMethod("is.rooted")

### ISSUE THREAD

**Issue by makerer5** [DaliangNing/iCAMP1#47]
Dear Ning
I tried to use the following R code to quantify the assembly process of microbial communities: wd0 = getwd()
save.wd = paste0(tempdir(),"/pdbig")
nworker=6
rand.time = 1000
bin.size.limit = 24
otu <- read.table("otutab.txt", header = TRUE, row.names = 1, stringsAsFactors = FALSE, comment.char = "")
tree <- ape::read.tree("otus.nwk")
library(iCAMP)
icamp.out <- icamp.big(comm = otu,tree = tree,pd.wd = save.wd,rand = rand.time,nworker = nworker,bin.size.limit = bin.size.limit,ds = 0.2 ). But it failed, and the error message was as follows, "unexpected name: DMH40 DMH41 DMH42 DMH44
The names are re-ranked.
----------Now binning-----------------Sat Dec 9 12:54:23 2023
Error in UseMethod("is.rooted") :
   'is.rooted' has no method available for 'NULL' target object
Calls: icamp.big -> <Anonymous> -> is.rooted". 
I tried to find the answer on various websites, but no one encountered a similar situation. If you have time, can you help me find this error information
Thank you very much,
yang

**Comment by DaliangNing** [comment]
It looks like the tree file may have some problem. Please share your input files with me (ningdaliang@ou.edu) to debug.

By the way, you may check the example code for using iCAMP in  [https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r).

**Comment by makerer5** [comment]
Dear Ning
Thank you so much for responding to my message! The description and documents of the related problems have been sent to your mailbox.
Wishing you all the best,
Yang

**Comment by DaliangNing** [comment]
I hope your problem has been solved. If no more questions, i will close the issue soon.
