### ISSUE TITLE
Error in checkForRemoteErrors(val)

### ISSUE THREAD

**Issue by chenyj8** [DaliangNing/iCAMP1#48]
Hi Daliang,

I try to quantify the community assembly processes by using the following code:

`setwd(save.wd)
if(!file.exists("pd.desc")) 
{
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker, memory.G = memory.G)
}else{
  pd.big=list()
  pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
  pd.big$pd.wd=save.wd
  pd.big$pd.file="pd.desc"
  pd.big$pd.name.file="pd.taxon.name.csv"
}`

`iCAMP::qpen.cm(comm=comm,pd=pd.big$pd.file,pd.big.wd=pd.big$pd.wd,
                  pd.big.spname=pd.big$tip.label,ab.weight=TRUE,
                  rand.time=rand.time, nworker=nworker,project=prefix,
                  wd=save.wd, save.bNTIRC=TRUE, meta.group = metadata[,"habitat2",drop=F])`

However, I encountered the following error:

**Setting parallel cluster for path computing cost 1.400004 secs.  Tue Dec 19 13:42:17 2023
Parallel for 600 tips cost 1.988125 mins. Tue Dec 19 13:44:16 2023
Path computing by parallel may take 2.19445240951909 hours. Tue Dec 19 13:44:18 2023
Now computing path for the rest 39666 tips. begin at Tue Dec 19 13:44:19 2023. Please wait...
Computing path for the rest 39666 tips actually took 2.771099 mins. Tue Dec 19 13:47:04 2023
Now setting big matrix file on the disk. Tue Dec 19 13:47:05 2023
Setting parallel cluster for pdist computing cost 1.330648 secs.  Tue Dec 19 13:47:20 2023
Parallel computing Pdist for the first 600 runs cost 2.446895 mins. Tue Dec 19 13:49:47 2023
The rest Pdist computing by parallel may take 1.33220872485118 hours. Tue Dec 19 13:49:47 2023
Computing pdist for the rest 39666 tips actually took 16.60026 mins. Tue Dec 19 14:06:23 2023
All match very well.
The names are re-ranked.
All match very well.
All match very well.
Now calculating observed betaMNTD. Begin at Tue Dec 19 14:06:33 2023. Please wait...
Now randomizing by parallel computing. Begin at Tue Dec 19 14:18:16 2023. Please wait...
Error in checkForRemoteErrors(val) : 
  120 nodes produced errors; first error: incorrect number of subscripts on matrix
Calls: <Anonymous> ... clusterApply -> staticClusterApply -> checkForRemoteErrors
In addition: Warning message:
'memory.size()' is Windows-specific 
Execution halted**

**Comment by DaliangNing** [comment]
It looks like some format issue. Please send me (ningdaliang@ou.edu) your input files and R code file to debug.

**Comment by DaliangNing** [comment]
The bug is caused by format. I have corrected the related functions. Please use version 1.6.5 in [https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions).

**Comment by chenyj8** [comment]
> The bug is caused by format. I have corrected the related functions. Please use version 1.6.5 in https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions.

Thank you. It works after updating iCAMP to 1.6.5.
