### ISSUE TITLE
How to get the category information?

### ISSUE THREAD

**Issue by XELong** [DaliangNing/iCAMP1#50]
Dear Dr. Ning
I would like to use the package iCAMP to analyze my own data. However, I don't know how to get the category information. Core, others, and rare OTU definitions were based on their relative abundance from the OTU table ? What is the threshold value for core, others, or rare otu?

Best wishes

Long

**Comment by DaliangNing** [comment]
Category information depends on the scientific questions in your research. You may investigate the literature. Different researchers defined core and rare taxa in different ways.  Category can also be phyla, family, or any other classification of taxa according to hypothesis you want to test.

**Comment by XELong** [comment]
Thanks for your response. I also find the answer for this paper https://doi.org/10.3389/fmicb.2020.589164, they define core OTUs according to the relative abundance.
