### ISSUE TITLE
Stuck at phylogentic signal testing

### ISSUE THREAD

**Issue by jonaskohh** [DaliangNing/iCAMP1#51]
Hello, 

I have been following the steps as shown in the example on my dataset but I am currently stuck in the function ps.bin, with the error:

Error in cor(as.vector(xdis), ydis, method = method, use = use) : 
  missing observations in cov/cor
Calls: <Anonymous> ... FUN -> sapply -> lapply -> FUN -> <Anonymous> -> cor
Execution halted

Can I get help on this as I am not sure what is wrong? Thank you!
[bnti_Rout.pdf](https://github.com/DaliangNing/iCAMP1/files/14353056/bnti_Rout.pdf)

**Comment by DaliangNing** [comment]
you may send me (ningdaliang@ou.edu) your input files and R code. I will try to debug.
