### ISSUE TITLE
Protocols for using HPC?

### ISSUE THREAD

**Issue by cckeneally** [DaliangNing/iCAMP1#54]
Hi,

I have been running into memory issues on a local machine when running icamp.big on a ~45,000 taxa dataset (it gets through each bin individually, but memory util rapidly expands at the end and crashes r.).
So, I am now going to try running icamp on a HPC.

On an HPC, are the bigmemory methods are still applicable?
For example, can _pdist.p_ be used to calculate pairwise distance rather than _pdist.big_?
As bigmemory utilises disk memory instead of RAM, are there any extra steps required, or is this specific to the HPC?

Thank you for your hard work on this package!

**Comment by DaliangNing** [comment]
Which step gave you the error? You may test the latest version of iCAMP (version 1.6.5). I know some previous versions may have this issue during phylogenetic signal test, which has been solved in recent versions. All versions are available from [https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions). 

We have not tried HPC. Theoretically, it should be fine.

**Comment by cckeneally** [comment]
I was having issues with IO limitation between filesystem and compute nodes when using bigmatrix functions.
For the benefit of any others with similar issues:
This was solved by using $TMPDIR (job specific storage), as shown in the slurm script below:

`#!/bin/bash -l
#SBATCH -p highmem                                             # partition
#SBATCH -N 1                                                   # number of nodes
#SBATCH -n 72                                                  # number of cores
#SBATCH --time=3-00:00:00                                      # walltime (D-HH:MM:SS)
#SBATCH --mem=1000GB                                           # memory per node
#SBATCH --gres=tmpfs:200G                                      # requesting tmpfs

echo "Starting Job at $(date)"
echo "Job ID: $SLURM_JOB_ID running on node: $SLURMD_NODENAME"

# Load R module and set R library path
module load R
export R_LIBS_USER=/path/to/R/Libs

echo "R module loaded, R_LIBS_USER set to $R_LIBS_USER"

# Define target directory in persistent storage
PERSISTENT_DIR="/path/to/persistant/storage"
echo "Output will be copied to $PERSISTENT_DIR at the end of the job"

# Ensure the target directory exists
mkdir -p $PERSISTENT_DIR
echo "Ensured $PERSISTENT_DIR exists"

# Run the R script, passing the TMPDIR (automatically created tmpfs path) as an argument
echo "Running R script with temporary directory $TMPDIR"
Rscript /path/to/icamp/script $TMPDIR

# Check if R script ran successfully
if [ $? -eq 0 ]; then
    echo "R script completed successfully"
else
    echo "R script failed with exit code $?"
fi

# Copy the results from tmpfs to the new directory in persistent storage
echo "Copying results from $TMPDIR to $PERSISTENT_DIR"
cp -r $TMPDIR/* $PERSISTENT_DIR

echo "Copy operation completed, job finished at $(date)"`

iCAMP package worked perfectly on the HPC using this approach

**Comment by DaliangNing** [comment]
Thank you : )
