### ISSUE TITLE
requirement of the sample number

### ISSUE THREAD

**Issue by Gu2uMo** [DaliangNing/iCAMP1#55]
Hi ,
I have a question about requirement of the sample number for iCAMP.
For instance, if there are only 6 sample, is the result still reliable ?
Any suggestions for how many samples should be prepared at least 

Thanks.

**Comment by DaliangNing** [comment]
Strictly speaking, it can be case-dependent. However, till now, we do not have a tool to identify the minimal requirement of sample size for iCAMP. In 2019 (Fig S2 in [https://doi.org/10.1073/pnas.190462311](https://doi.org/10.1073/pnas.1904623116)), we explored this issue with simulated data, where 6 samples can be the minimal requirement for null model analysis of the simulated dataset.

**Comment by Gu2uMo** [comment]
Thanks！
