### ISSUE TITLE
Fatal error: Exit code 1 () Now computing path. begin at Sat May 11 22:04:08 2024. Please wait... Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: subscript out of bounds Calls: ... clusterApply -> staticClusterAp

### ISSUE THREAD

**Issue by kelly-xia** [DaliangNing/iCAMP1#58]
Dear Professor:
I encountered the following issues when conducting diversity analysis of iCAMP on Galaxy. I am not sure where the problem lies. Could you show and help me figure it out? My account is [31000655@scau.edu.cn](mailto:31000655@scau.edu.cn). I am looking forward to your reply. Thank you so much.

Fatal error: Exit code 1 ()
Now computing path. begin at Sat May 11 22:04:08 2024. Please wait...
Error in checkForRemoteErrors(val) :
2 nodes produced errors; first error: subscript out of bounds
Calls: ... clusterApply -> staticClusterAp

Your Sincerely
Kelly

**Comment by fen111-create** [comment]
I meet a similar problem and i have sloved. The arguement "comm" need a input of matrix. It runs when arguement "comm" is converted to a matrix.

**Comment by DaliangNing** [comment]
@kelly-xia  iCAMP is a R package, thus it is 'case-sensitive'. The taxa IDs in your tree file start with 'Otu', but the taxa IDs in your OTU table and classification table start with 'OTU'. need to make them consistent.
