### ISSUE TITLE
How to build a bin level phylogenetic tree

### ISSUE THREAD

**Issue by xcljnu** [DaliangNing/iCAMP1#59]
Dear Daliang Ning 
You developed a very good R package, but I encountered some doubts in the specific application. Based on the sample data you provided, in the result folder TestOutputs, I did not find the tree file used to build the bin level phylogenetic tree. I would like to ask you to provide some help so that I can show bin level phylogenetic tree like the figure in your article. Thank you !

**Comment by DaliangNing** [comment]
@xcljnu 
(1) Generate bins' phylogenetic tree.
I generally use the most abundant OTU (or ASV) in a bin to represent the bin (the output ...Bin_TopTaxon.csv can provide the information), then extract Tree of bins for the entire Tree using the function keep.tip in R package ape.
I do see some users draw the entire tree and give different bins different colors or label each bin, which can be nice if there are not too many OTUs (or ASV).

(2) Visualize the tree and statistics of each bin
My previous tree-plot code is difficult for other people to use, and the generated figure still needs quite a few edits on annotation. 
Some iCAMP users recently drew very beautiful tree plots of iCAMP results by using iTOL (https://itol.embl.de/). You may explore : )
