### ISSUE TITLE
Correlate bin-level processes with environmental variates

### ISSUE THREAD

**Issue by adityabandla** [DaliangNing/iCAMP1#6]
Dear Ning,

It would be great to have a function which can correlate bin-level ecological processes (as you do in your paper) with environmental variables using Mantel tests/MRM

Cheers, Adi

**Comment by DaliangNing** [comment]
I will try to get it done as soon as I can. For now, you may find the code I used for Mantel test/MRM analysis in the paper.
https://github.com/DaliangNing/iCAMP1/tree/master/Publication1/Code/EmpiricalStudy

**Comment by adityabandla** [comment]
@DaliangNing I was able to use the codes from the link to reproduce mantel lm, glm, mantel, and partial mantel results. However, I am a bit lost as to how to get MRM results (Fig 5 b & c) you show in the paper i.e. regression co-efficients, explained variation etc. Any help/pointers would be much appreciated

**Comment by DaliangNing** [comment]
[https://github.com/DaliangNing/iCAMP1/blob/master/Publication1/Code/EmpiricalStudy/MRM.20200822.r](https://github.com/DaliangNing/iCAMP1/blob/master/Publication1/Code/EmpiricalStudy/MRM.20200822.r)
is for MRM.
the regression coefficients can be found in mod.obs.
R2.obs is the explained variation by the whole model.
p values can be found in the output of 'data.frame' line under t.rand.

**Comment by adityabandla** [comment]
Hi Ning, sorry for being unresponsive. I was only able to reproduce it up to a certain point and didn't get around to check the rest. I will close this now and get back if I have more questions. Thanks once again for being very helpful! :)

**Comment by ARetter90** [comment]
Hi,

I am trying to run the correlation of my icamp results with my environmental parameters, but always get a warning ("the combination of grp info is not unique ID. may use random match when permutation") and the error: 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': length of 'dimnames' [2] not equal to array extent
when I define my random variables "season" and "Cluster" from my treatment file when running any of the regression functions.

I attach for you the csv files - maybe you are able to reproduce the error and solve the issue, would be highly appreciated.

Thanks,
Alice
[OKCW5Y.geoenv.tempc - Copy.csv]
(https://github.com/DaliangNing/iCAMP1/files/10456139/OKCW5Y.geoenv.tempc.-.Copy.csv)
[OKCW5Y.Coordinates - Copy.csv](https://github.com/DaliangNing/iCAMP1/files/10456141/OKCW5Y.Coordinates.-.Copy.csv)
[OKCW5Y.T1R1000.iCAMP.bNRIiRCa.sum - Copy.csv](https://github.com/DaliangNing/iCAMP1/files/10456142/OKCW5Y.T1R1000.iCAMP.bNRIiRCa.sum.-.Copy.csv)
[OKCW5Y.Treatment - Copy.csv](https://github.com/DaliangNing/iCAMP1/files/10456143/OKCW5Y.Treatment.-.Copy.csv)
