### ISSUE TITLE
Extremely fast phylogenetic distance computation

### ISSUE THREAD

**Issue by jianshu93** [DaliangNing/iCAMP1#61]
Hi Daliang, 

I ran into this Rust package (https://github.com/aaronmussig/PhyloDM) recently that can be more than 100 faster than the R and python package for calculating phylogenetic distance among leaves for very large tree. I remember this is the limiting step among all other steps for betaNTI and all other methods built upon it. This is only a python API but I think it is easy to call python within R. 

Thanks,

Jianshu

**Comment by DaliangNing** [comment]
Jianshu, thank you, this is a nice tool! however, for large datasets, the bottleneck of iCAMP is not phylogenetic distance but the phylogenetic null model calculation.
