### ISSUE TITLE
Optimizing Binning: MeanR vs. RAsig.adj?

### ISSUE THREAD

**Issue by gus-pendleton** [DaliangNing/iCAMP1#62]
Hi Dr. Ning,

I've really enjoyed working the iCAMP package - thank you for this resource!

I am trying to pick the best parameters for phylogenetic binning. I binned across a range of distances ("ds") and minimum bin sizes ("bin.size.limit") and then tested signal strength across my environmental variables using `ps.bin`. 

Here are my results:
![image](https://github.com/user-attachments/assets/adcbdcaf-ecaa-4ad8-b981-782242667b25)

Clearly, the mean correlation within bin is optimized with smaller bins. In contrast, I get my maximum number of bins with a significant signal using a larger bin size limit (bin.size.limit = 48). 

I'm curious on your advice whether it's more important to maximize:
- RAsig.adj, in which case I would use `ds = 0.3, bin.size.limit = 48`
- MeanR, in which case I would use `ds = 0.3, bin.size.limit = 12`
- Or a compromise between the two, where I might use `ds = 0.4, bin.size.limit = 36`

Thank you!

Gus

**Comment by DaliangNing** [comment]
@gus-pendleton it is always more important to get bigger RAsig.adj.  Only use MeanR when RAsig.adj is the same or very simialr between different settings.
