### ISSUE TITLE
icamp.big debug problem

### ISSUE THREAD

**Issue by sssbishop** [DaliangNing/iCAMP1#63]
Hello,Mr Ning Daliang:
When I run the icamp.big,there is aways a error.
![image](https://github.com/user-attachments/assets/b4e7ff0b-f534-463b-b19c-2a7fb806e97e)
I have checked the input txt for several times to ensure the format is right but errors keep occuring.I have sent the .R file and the input txt to your email.
Thank you for your  help!

**Comment by DaliangNing** [comment]
@sssbishop this is probably due to format issue. Please send me (ningdaliang@ou.edu) your R code and input files to debug.

**Comment by DaliangNing** [comment]
@sssbishop I notice you said you have already sent me your files. Please send me again if you did not receive my response.
