### ISSUE TITLE
how to change the control and treatment groups when doing a bootstrapping analysis using icamp.boot?

### ISSUE THREAD

**Issue by kangluyao** [DaliangNing/iCAMP1#67]
Dear Dr. Ning, thanks for your excellent work on iCAMP. I'm writing to seek clarification regarding the icamp.boot function, specifically about setting the control group for bootstrapping analysis. My understanding is that group1 represents the treatment group, while group2 serves as the control.  I've attempted to factor the treatment with a specific order, but it doesn't work. Could you please tell me how to manage this? I'm using version 1.5.12 of iCAMP with R-4.4.1. Thanks!

**Comment by DaliangNing** [comment]
@kangluyao  it should work as showed in the example code [https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r). You may send me your code and input files (better also the "...detail.rda" file generated from icamp.big function), to debug.

**Comment by kangluyao** [comment]
Hi, Dr. Ning, thank you for your prompt response. I have sent you an email containing my data and the corresponding results as attachments. Your assistance is greatly appreciated. Please let me know if you need any additional information or clarification.

**Comment by kangluyao** [comment]
Hi Dr. Ning, Thank you so much for your reply and your hard work on iCAMP. It's exactly what I was looking for. I will go ahead and rerun the code.
